// This file is generated by scripts/generate-locales.mjs.
// Do not edit it by hand.

export const defaultLocale = "en" as const;

export const localeCatalog = {
  "de": {
    "meta": {
      "name": "Better Reviews for Amazon",
      "description": "Lässt Produktbewertungen auf Amazon-Seiten vertrauenswürdiger wirken."
    },
    "ui": {
      "loading": "Bewertungsdaten werden geladen…",
      "verifiedPurchaseReviews": "Bewertungen mit verifiziertem Kauf",
      "criticalReviews": "Kritische Bewertungen",
      "positiveReviews": "Positive Bewertungen",
      "vineReviews": "Vine-Bewertungen",
      "cachedLabel": "Cache",
      "cachedTitle": "Zwischengespeicherte Daten werden angezeigt, weil die Live-Bewertungsseiten nicht verfügbar waren.",
      "errorUnavailable": "Bewertungsdaten nicht verfügbar",
      "errorSignInRequired": "Bewertungsdaten nicht verfügbar — Anmeldung erforderlich"
    }
  },
  "en": {
    "meta": {
      "name": "Better Reviews for Amazon",
      "description": "Makes product reviews look more trustworthy on Amazon pages."
    },
    "ui": {
      "loading": "Loading review stats…",
      "verifiedPurchaseReviews": "Verified purchase reviews",
      "criticalReviews": "Critical reviews",
      "positiveReviews": "Positive reviews",
      "vineReviews": "Vine reviews",
      "cachedLabel": "cached",
      "cachedTitle": "Showing cached data because the live review pages were unavailable.",
      "errorUnavailable": "Review stats unavailable",
      "errorSignInRequired": "Review stats unavailable — sign in required"
    }
  },
  "ru": {
    "meta": {
      "name": "Better Reviews for Amazon",
      "description": "Делает отзывы о товарах на страницах Amazon более заслуживающими доверия."
    },
    "ui": {
      "loading": "Загрузка данных отзывов…",
      "verifiedPurchaseReviews": "Отзывы с подтверждённой покупкой",
      "criticalReviews": "Критические отзывы",
      "positiveReviews": "Положительные отзывы",
      "vineReviews": "Отзывы Vine",
      "cachedLabel": "кэш",
      "cachedTitle": "Показаны данные из кэша, потому что страницы отзывов сейчас недоступны.",
      "errorUnavailable": "Данные отзывов недоступны",
      "errorSignInRequired": "Данные отзывов недоступны — нужен вход в аккаунт"
    }
  }
} as const;

export type SupportedLocale = keyof typeof localeCatalog;
export type LocaleMessages = (typeof localeCatalog)[SupportedLocale];
