import { readdir, readFile, writeFile } from 'node:fs/promises';

const localesDir = new URL('../src/i18n/locales/', import.meta.url);
const outputFile = new URL('../src/i18n/generated.ts', import.meta.url);
const defaultLocale = 'en';

const localeFiles = (await readdir(localesDir))
  .filter((fileName) => fileName.endsWith('.json'))
  .sort((left, right) => left.localeCompare(right));

if (!localeFiles.includes(`${defaultLocale}.json`)) {
  throw new Error(`Missing default locale file: ${defaultLocale}.json`);
}

const localeCatalog = {};
for (const fileName of localeFiles) {
  const locale = fileName.replace(/\.json$/u, '');
  const content = await readFile(new URL(fileName, localesDir), 'utf8');
  localeCatalog[locale] = JSON.parse(content);
}

const baseLocale = localeCatalog[defaultLocale];
for (const [locale, messages] of Object.entries(localeCatalog)) {
  validateLocaleShape(baseLocale, messages, locale);
}

const output = `// This file is generated by scripts/generate-locales.mjs.
// Do not edit it by hand.

export const defaultLocale = ${JSON.stringify(defaultLocale)} as const;

export const localeCatalog = ${JSON.stringify(localeCatalog, null, 2)} as const;

export type SupportedLocale = keyof typeof localeCatalog;
export type LocaleMessages = (typeof localeCatalog)[SupportedLocale];
`;

await writeFile(outputFile, output, 'utf8');

function validateLocaleShape(expected, actual, locale, path = []) {
  if (Array.isArray(expected) || Array.isArray(actual)) {
    throw new Error(`Arrays are not supported in locale data (${locale}:${formatPath(path)}).`);
  }

  for (const key of Object.keys(expected)) {
    if (!(key in actual)) {
      throw new Error(`Missing locale key "${formatPath([...path, key])}" in ${locale}.`);
    }

    const expectedValue = expected[key];
    const actualValue = actual[key];

    if (isPlainObject(expectedValue) && isPlainObject(actualValue)) {
      validateLocaleShape(expectedValue, actualValue, locale, [...path, key]);
      continue;
    }

    if (typeof expectedValue !== typeof actualValue) {
      throw new Error(`Locale key "${formatPath([...path, key])}" in ${locale} has a mismatched type.`);
    }
  }

  for (const key of Object.keys(actual)) {
    if (!(key in expected)) {
      throw new Error(`Unexpected locale key "${formatPath([...path, key])}" in ${locale}.`);
    }
  }
}

function isPlainObject(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function formatPath(path) {
  return path.join('.');
}
